language: node_js
node_js:
  - "7"
install:
  - npm install
script:
  - npm start
  - npm run ghtest
  - npm test
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: 'dist'
    github_token: $GITHUB_TOKEN_A
    on:
      branch: master
